// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dislserver.proto

package ch.usi.dag.dislserver;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code InstrumentClassResult}
   */
  public enum InstrumentClassResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    CLASS_UNMODIFIED(0),
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    CLASS_MODIFIED(1),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    public static final int CLASS_UNMODIFIED_VALUE = 0;
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    public static final int CLASS_MODIFIED_VALUE = 1;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InstrumentClassResult valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static InstrumentClassResult forNumber(int value) {
      switch (value) {
        case 0: return CLASS_UNMODIFIED;
        case 1: return CLASS_MODIFIED;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InstrumentClassResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>() {
            public InstrumentClassResult findValueByNumber(int number) {
              return InstrumentClassResult.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ch.usi.dag.dislserver.Protocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final InstrumentClassResult[] VALUES = values();

    public static InstrumentClassResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InstrumentClassResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InstrumentClassResult)
  }

  public interface InstrumentClassRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    int getFlags();

    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassRequest}
   */
  public  static final class InstrumentClassRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InstrumentClassRequest)
      InstrumentClassRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstrumentClassRequest.newBuilder() to construct.
    private InstrumentClassRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstrumentClassRequest() {
      className_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InstrumentClassRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstrumentClassRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              flags_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 26: {

              classBytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.class, ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.Builder.class);
    }

    public static final int FLAGS_FIELD_NUMBER = 1;
    private int flags_;
    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    public int getFlags() {
      return flags_;
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object className_;
    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (flags_ != 0) {
        output.writeInt32(1, flags_);
      }
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_);
      }
      if (!classBytes_.isEmpty()) {
        output.writeBytes(3, classBytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (flags_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flags_);
      }
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, className_);
      }
      if (!classBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, classBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.usi.dag.dislserver.Protocol.InstrumentClassRequest)) {
        return super.equals(obj);
      }
      ch.usi.dag.dislserver.Protocol.InstrumentClassRequest other = (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest) obj;

      if (getFlags()
          != other.getFlags()) return false;
      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getClassBytes()
          .equals(other.getClassBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFlags();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + CLASSBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getClassBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InstrumentClassRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassRequest)
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.class, ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.Builder.class);
      }

      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        flags_ = 0;

        className_ = "";

        classBytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassRequest_descriptor;
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstanceForType() {
        return ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassRequest build() {
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassRequest buildPartial() {
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequest result = new ch.usi.dag.dislserver.Protocol.InstrumentClassRequest(this);
        result.flags_ = flags_;
        result.className_ = className_;
        result.classBytes_ = classBytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.usi.dag.dislserver.Protocol.InstrumentClassRequest) {
          return mergeFrom((ch.usi.dag.dislserver.Protocol.InstrumentClassRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.usi.dag.dislserver.Protocol.InstrumentClassRequest other) {
        if (other == ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.getDefaultInstance()) return this;
        if (other.getFlags() != 0) {
          setFlags(other.getFlags());
        }
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (other.getClassBytes() != com.google.protobuf.ByteString.EMPTY) {
          setClassBytes(other.getClassBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int flags_ ;
      /**
       * <code>int32 flags = 1;</code>
       * @return The flags.
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <code>int32 flags = 1;</code>
       * @param value The flags to set.
       * @return This builder for chaining.
       */
      public Builder setFlags(int value) {
        
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flags = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlags() {
        
        flags_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>string className = 2;</code>
       * @return The className.
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString classBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      public com.google.protobuf.ByteString getClassBytes() {
        return classBytes_;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        classBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        
        classBytes_ = getDefaultInstance().getClassBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InstrumentClassRequest)
    }

    // @@protoc_insertion_point(class_scope:InstrumentClassRequest)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.usi.dag.dislserver.Protocol.InstrumentClassRequest();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstrumentClassRequest>
        PARSER = new com.google.protobuf.AbstractParser<InstrumentClassRequest>() {
      @java.lang.Override
      public InstrumentClassRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstrumentClassRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstrumentClassRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstrumentClassRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstrumentClassResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult();

    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassResponse}
   */
  public  static final class InstrumentClassResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InstrumentClassResponse)
      InstrumentClassResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstrumentClassResponse.newBuilder() to construct.
    private InstrumentClassResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstrumentClassResponse() {
      result_ = 0;
      errorMessage_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InstrumentClassResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstrumentClassResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMessage_ = s;
              break;
            }
            case 26: {

              classBytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.class, ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
      @SuppressWarnings("deprecation")
      ch.usi.dag.dislserver.Protocol.InstrumentClassResult result = ch.usi.dag.dislserver.Protocol.InstrumentClassResult.valueOf(result_);
      return result == null ? ch.usi.dag.dislserver.Protocol.InstrumentClassResult.UNRECOGNIZED : result;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != ch.usi.dag.dislserver.Protocol.InstrumentClassResult.CLASS_UNMODIFIED.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
      }
      if (!classBytes_.isEmpty()) {
        output.writeBytes(3, classBytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != ch.usi.dag.dislserver.Protocol.InstrumentClassResult.CLASS_UNMODIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
      }
      if (!classBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, classBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.usi.dag.dislserver.Protocol.InstrumentClassResponse)) {
        return super.equals(obj);
      }
      ch.usi.dag.dislserver.Protocol.InstrumentClassResponse other = (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse) obj;

      if (result_ != other.result_) return false;
      if (!getErrorMessage()
          .equals(other.getErrorMessage())) return false;
      if (!getClassBytes()
          .equals(other.getClassBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (37 * hash) + CLASSBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getClassBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InstrumentClassResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassResponse)
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.class, ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.Builder.class);
      }

      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        errorMessage_ = "";

        classBytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.usi.dag.dislserver.Protocol.internal_static_InstrumentClassResponse_descriptor;
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstanceForType() {
        return ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResponse build() {
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResponse buildPartial() {
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponse result = new ch.usi.dag.dislserver.Protocol.InstrumentClassResponse(this);
        result.result_ = result_;
        result.errorMessage_ = errorMessage_;
        result.classBytes_ = classBytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.usi.dag.dislserver.Protocol.InstrumentClassResponse) {
          return mergeFrom((ch.usi.dag.dislserver.Protocol.InstrumentClassResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.usi.dag.dislserver.Protocol.InstrumentClassResponse other) {
        if (other == ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.getClassBytes() != com.google.protobuf.ByteString.EMPTY) {
          setClassBytes(other.getClassBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The result.
       */
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
        @SuppressWarnings("deprecation")
        ch.usi.dag.dislserver.Protocol.InstrumentClassResult result = ch.usi.dag.dislserver.Protocol.InstrumentClassResult.valueOf(result_);
        return result == null ? ch.usi.dag.dislserver.Protocol.InstrumentClassResult.UNRECOGNIZED : result;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>string errorMessage = 2;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString classBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      public com.google.protobuf.ByteString getClassBytes() {
        return classBytes_;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        classBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        
        classBytes_ = getDefaultInstance().getClassBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InstrumentClassResponse)
    }

    // @@protoc_insertion_point(class_scope:InstrumentClassResponse)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.usi.dag.dislserver.Protocol.InstrumentClassResponse();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstrumentClassResponse>
        PARSER = new com.google.protobuf.AbstractParser<InstrumentClassResponse>() {
      @java.lang.Override
      public InstrumentClassResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstrumentClassResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstrumentClassResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstrumentClassResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstrumentClassRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstrumentClassRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstrumentClassResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstrumentClassResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dislserver.proto\"N\n\026InstrumentClassReq" +
      "uest\022\r\n\005flags\030\001 \001(\005\022\021\n\tclassName\030\002 \001(\t\022\022" +
      "\n\nclassBytes\030\003 \001(\014\"k\n\027InstrumentClassRes" +
      "ponse\022&\n\006result\030\001 \001(\0162\026.InstrumentClassR" +
      "esult\022\024\n\014errorMessage\030\002 \001(\t\022\022\n\nclassByte" +
      "s\030\003 \001(\014*L\n\025InstrumentClassResult\022\024\n\020CLAS" +
      "S_UNMODIFIED\020\000\022\022\n\016CLASS_MODIFIED\020\001\022\t\n\005ER" +
      "ROR\020\003B#\n\025ch.usi.dag.dislserverB\010Protocol" +
      "H\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InstrumentClassRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InstrumentClassRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstrumentClassRequest_descriptor,
        new java.lang.String[] { "Flags", "ClassName", "ClassBytes", });
    internal_static_InstrumentClassResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InstrumentClassResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstrumentClassResponse_descriptor,
        new java.lang.String[] { "Result", "ErrorMessage", "ClassBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
