// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dislserver.proto

package ch.usi.dag.dislserver;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code InstrumentClassResult}
   */
  public enum InstrumentClassResult
          implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    CLASS_UNMODIFIED(0),
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    CLASS_MODIFIED(1),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    public static final int CLASS_UNMODIFIED_VALUE = 0;
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    public static final int CLASS_MODIFIED_VALUE = 1;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InstrumentClassResult valueOf(int value) {
      return forNumber(value);
    }

    public static InstrumentClassResult forNumber(int value) {
      switch (value) {
        case 0: return CLASS_UNMODIFIED;
        case 1: return CLASS_MODIFIED;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
            InstrumentClassResult> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>() {
              @java.lang.Override
              public InstrumentClassResult findValueByNumber(int number) {
                return InstrumentClassResult.forNumber(number);
              }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
      return InstrumentClassResultVerifier.INSTANCE;
    }

    private static final class InstrumentClassResultVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
      static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new InstrumentClassResultVerifier();
      @java.lang.Override
      public boolean isInRange(int number) {
        return InstrumentClassResult.forNumber(number) != null;
      }
    };

    private final int value;

    private InstrumentClassResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InstrumentClassResult)
  }

  /**
   * Protobuf enum {@code ControllerAction}
   */
  public enum ControllerAction
          implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>DEPLOY = 0;</code>
     */
    DEPLOY(0),
    /**
     * <code>UNDEPLOY = 1;</code>
     */
    UNDEPLOY(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEPLOY = 0;</code>
     */
    public static final int DEPLOY_VALUE = 0;
    /**
     * <code>UNDEPLOY = 1;</code>
     */
    public static final int UNDEPLOY_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ControllerAction valueOf(int value) {
      return forNumber(value);
    }

    public static ControllerAction forNumber(int value) {
      switch (value) {
        case 0: return DEPLOY;
        case 1: return UNDEPLOY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ControllerAction>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
            ControllerAction> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ControllerAction>() {
              @java.lang.Override
              public ControllerAction findValueByNumber(int number) {
                return ControllerAction.forNumber(number);
              }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
      return ControllerActionVerifier.INSTANCE;
    }

    private static final class ControllerActionVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
      static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ControllerActionVerifier();
      @java.lang.Override
      public boolean isInRange(int number) {
        return ControllerAction.forNumber(number) != null;
      }
    };

    private final int value;

    private ControllerAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ControllerAction)
  }

  /**
   * Protobuf enum {@code ControllerResult}
   */
  public enum ControllerResult
          implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>KO = 1;</code>
     */
    KO(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>KO = 1;</code>
     */
    public static final int KO_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ControllerResult valueOf(int value) {
      return forNumber(value);
    }

    public static ControllerResult forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return KO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ControllerResult>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
            ControllerResult> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ControllerResult>() {
              @java.lang.Override
              public ControllerResult findValueByNumber(int number) {
                return ControllerResult.forNumber(number);
              }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
      return ControllerResultVerifier.INSTANCE;
    }

    private static final class ControllerResultVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
      static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ControllerResultVerifier();
      @java.lang.Override
      public boolean isInRange(int number) {
        return ControllerResult.forNumber(number) != null;
      }
    };

    private final int value;

    private ControllerResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ControllerResult)
  }

  public interface InstrumentClassRequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:InstrumentClassRequest)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    int getFlags();

    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
    getClassNameBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();

    /**
     * <code>int32 classLoaderTag = 4;</code>
     * @return The classLoaderTag.
     */
    int getClassLoaderTag();

    /**
     * <code>bytes classLoaderBytes = 5;</code>
     * @return The classLoaderBytes.
     */
    com.google.protobuf.ByteString getClassLoaderBytes();

    /**
     * <code>bytes superTypesBytes = 6;</code>
     * @return The superTypesBytes.
     */
    com.google.protobuf.ByteString getSuperTypesBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassRequest}
   */
  public  static final class InstrumentClassRequest extends
          com.google.protobuf.GeneratedMessageLite<
                  InstrumentClassRequest, InstrumentClassRequest.Builder> implements
          // @@protoc_insertion_point(message_implements:InstrumentClassRequest)
          InstrumentClassRequestOrBuilder {
    private InstrumentClassRequest() {
      className_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
      classLoaderBytes_ = com.google.protobuf.ByteString.EMPTY;
      superTypesBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FLAGS_FIELD_NUMBER = 1;
    private int flags_;
    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>int32 flags = 1;</code>
     * @param value The flags to set.
     */
    private void setFlags(int value) {

      flags_ = value;
    }
    /**
     * <code>int32 flags = 1;</code>
     */
    private void clearFlags() {

      flags_ = 0;
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.String className_;
    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      return className_;
    }
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getClassNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(className_);
    }
    /**
     * <code>string className = 2;</code>
     * @param value The className to set.
     */
    private void setClassName(
            java.lang.String value) {
      value.getClass();

      className_ = value;
    }
    /**
     * <code>string className = 2;</code>
     */
    private void clearClassName() {

      className_ = getDefaultInstance().getClassName();
    }
    /**
     * <code>string className = 2;</code>
     * @param value The bytes for className to set.
     */
    private void setClassNameBytes(
            com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      className_ = value.toStringUtf8();

    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     * @param value The classBytes to set.
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      value.getClass();

      classBytes_ = value;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {

      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public static final int CLASSLOADERTAG_FIELD_NUMBER = 4;
    private int classLoaderTag_;
    /**
     * <code>int32 classLoaderTag = 4;</code>
     * @return The classLoaderTag.
     */
    @java.lang.Override
    public int getClassLoaderTag() {
      return classLoaderTag_;
    }
    /**
     * <code>int32 classLoaderTag = 4;</code>
     * @param value The classLoaderTag to set.
     */
    private void setClassLoaderTag(int value) {

      classLoaderTag_ = value;
    }
    /**
     * <code>int32 classLoaderTag = 4;</code>
     */
    private void clearClassLoaderTag() {

      classLoaderTag_ = 0;
    }

    public static final int CLASSLOADERBYTES_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString classLoaderBytes_;
    /**
     * <code>bytes classLoaderBytes = 5;</code>
     * @return The classLoaderBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassLoaderBytes() {
      return classLoaderBytes_;
    }
    /**
     * <code>bytes classLoaderBytes = 5;</code>
     * @param value The classLoaderBytes to set.
     */
    private void setClassLoaderBytes(com.google.protobuf.ByteString value) {
      value.getClass();

      classLoaderBytes_ = value;
    }
    /**
     * <code>bytes classLoaderBytes = 5;</code>
     */
    private void clearClassLoaderBytes() {

      classLoaderBytes_ = getDefaultInstance().getClassLoaderBytes();
    }

    public static final int SUPERTYPESBYTES_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString superTypesBytes_;
    /**
     * <code>bytes superTypesBytes = 6;</code>
     * @return The superTypesBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSuperTypesBytes() {
      return superTypesBytes_;
    }
    /**
     * <code>bytes superTypesBytes = 6;</code>
     * @param value The superTypesBytes to set.
     */
    private void setSuperTypesBytes(com.google.protobuf.ByteString value) {
      value.getClass();

      superTypesBytes_ = value;
    }
    /**
     * <code>bytes superTypesBytes = 6;</code>
     */
    private void clearSuperTypesBytes() {

      superTypesBytes_ = getDefaultInstance().getSuperTypesBytes();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    ch.usi.dag.dislserver.Protocol.InstrumentClassRequest, Builder> implements
            // @@protoc_insertion_point(builder_implements:InstrumentClassRequest)
            ch.usi.dag.dislserver.Protocol.InstrumentClassRequestOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 flags = 1;</code>
       * @return The flags.
       */
      @java.lang.Override
      public int getFlags() {
        return instance.getFlags();
      }
      /**
       * <code>int32 flags = 1;</code>
       * @param value The flags to set.
       * @return This builder for chaining.
       */
      public Builder setFlags(int value) {
        copyOnWrite();
        instance.setFlags(value);
        return this;
      }
      /**
       * <code>int32 flags = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlags() {
        copyOnWrite();
        instance.clearFlags();
        return this;
      }

      /**
       * <code>string className = 2;</code>
       * @return The className.
       */
      @java.lang.Override
      public java.lang.String getClassName() {
        return instance.getClassName();
      }
      /**
       * <code>string className = 2;</code>
       * @return The bytes for className.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getClassNameBytes() {
        return instance.getClassNameBytes();
      }
      /**
       * <code>string className = 2;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
              java.lang.String value) {
        copyOnWrite();
        instance.setClassName(value);
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        copyOnWrite();
        instance.clearClassName();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
              com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassNameBytes(value);
        return this;
      }

      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      /**
       * <code>int32 classLoaderTag = 4;</code>
       * @return The classLoaderTag.
       */
      @java.lang.Override
      public int getClassLoaderTag() {
        return instance.getClassLoaderTag();
      }
      /**
       * <code>int32 classLoaderTag = 4;</code>
       * @param value The classLoaderTag to set.
       * @return This builder for chaining.
       */
      public Builder setClassLoaderTag(int value) {
        copyOnWrite();
        instance.setClassLoaderTag(value);
        return this;
      }
      /**
       * <code>int32 classLoaderTag = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassLoaderTag() {
        copyOnWrite();
        instance.clearClassLoaderTag();
        return this;
      }

      /**
       * <code>bytes classLoaderBytes = 5;</code>
       * @return The classLoaderBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClassLoaderBytes() {
        return instance.getClassLoaderBytes();
      }
      /**
       * <code>bytes classLoaderBytes = 5;</code>
       * @param value The classLoaderBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassLoaderBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassLoaderBytes(value);
        return this;
      }
      /**
       * <code>bytes classLoaderBytes = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassLoaderBytes() {
        copyOnWrite();
        instance.clearClassLoaderBytes();
        return this;
      }

      /**
       * <code>bytes superTypesBytes = 6;</code>
       * @return The superTypesBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSuperTypesBytes() {
        return instance.getSuperTypesBytes();
      }
      /**
       * <code>bytes superTypesBytes = 6;</code>
       * @param value The superTypesBytes to set.
       * @return This builder for chaining.
       */
      public Builder setSuperTypesBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSuperTypesBytes(value);
        return this;
      }
      /**
       * <code>bytes superTypesBytes = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuperTypesBytes() {
        copyOnWrite();
        instance.clearSuperTypesBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
                  "flags_",
                  "className_",
                  "classBytes_",
                  "classLoaderTag_",
                  "classLoaderBytes_",
                  "superTypesBytes_",
          };
          java.lang.String info =
                  "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                          "\u0003\n\u0004\u0004\u0005\n\u0006\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.InstrumentClassRequest> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                        new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.InstrumentClassRequest>(
                                DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassRequest)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassRequest DEFAULT_INSTANCE;
    static {
      InstrumentClassRequest defaultInstance = new InstrumentClassRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
              InstrumentClassRequest.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassRequest> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InstrumentClassResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:InstrumentClassResponse)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult();

    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
    getErrorMessageBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassResponse}
   */
  public  static final class InstrumentClassResponse extends
          com.google.protobuf.GeneratedMessageLite<
                  InstrumentClassResponse, InstrumentClassResponse.Builder> implements
          // @@protoc_insertion_point(message_implements:InstrumentClassResponse)
          InstrumentClassResponseOrBuilder {
    private InstrumentClassResponse() {
      errorMessage_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
      ch.usi.dag.dislserver.Protocol.InstrumentClassResult result = ch.usi.dag.dislserver.Protocol.InstrumentClassResult.forNumber(result_);
      return result == null ? ch.usi.dag.dislserver.Protocol.InstrumentClassResult.UNRECOGNIZED : result;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     */
    private void setResultValue(int value) {
      result_ = value;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @param value The result to set.
     */
    private void setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
      result_ = value.getNumber();

    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     */
    private void clearResult() {

      result_ = 0;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.String errorMessage_;
    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The errorMessage to set.
     */
    private void setErrorMessage(
            java.lang.String value) {
      value.getClass();

      errorMessage_ = value;
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    private void clearErrorMessage() {

      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The bytes for errorMessage to set.
     */
    private void setErrorMessageBytes(
            com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errorMessage_ = value.toStringUtf8();

    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     * @param value The classBytes to set.
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      value.getClass();

      classBytes_ = value;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {

      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    ch.usi.dag.dislserver.Protocol.InstrumentClassResponse, Builder> implements
            // @@protoc_insertion_point(builder_implements:InstrumentClassResponse)
            ch.usi.dag.dislserver.Protocol.InstrumentClassResponseOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override
      public int getResultValue() {
        return instance.getResultValue();
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        copyOnWrite();
        instance.setResultValue(value);
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
        return instance.getResult();
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>string errorMessage = 2;</code>
       * @return The errorMessage.
       */
      @java.lang.Override
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return The bytes for errorMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
              java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
              com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
                  "result_",
                  "errorMessage_",
                  "classBytes_",
          };
          java.lang.String info =
                  "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                          "\u0003\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.InstrumentClassResponse> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                        new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.InstrumentClassResponse>(
                                DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassResponse)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassResponse DEFAULT_INSTANCE;
    static {
      InstrumentClassResponse defaultInstance = new InstrumentClassResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
              InstrumentClassResponse.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassResponse> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ControllerRequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ControllerRequest)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.ControllerAction action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.ControllerAction action = 1;</code>
     * @return The action.
     */
    ch.usi.dag.dislserver.Protocol.ControllerAction getAction();

    /**
     * <code>string snippetName = 2;</code>
     * @return The snippetName.
     */
    java.lang.String getSnippetName();
    /**
     * <code>string snippetName = 2;</code>
     * @return The bytes for snippetName.
     */
    com.google.protobuf.ByteString
    getSnippetNameBytes();
  }
  /**
   * Protobuf type {@code ControllerRequest}
   */
  public  static final class ControllerRequest extends
          com.google.protobuf.GeneratedMessageLite<
                  ControllerRequest, ControllerRequest.Builder> implements
          // @@protoc_insertion_point(message_implements:ControllerRequest)
          ControllerRequestOrBuilder {
    private ControllerRequest() {
      snippetName_ = "";
    }
    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>.ControllerAction action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override
    public int getActionValue() {
      return action_;
    }
    /**
     * <code>.ControllerAction action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.ControllerAction getAction() {
      ch.usi.dag.dislserver.Protocol.ControllerAction result = ch.usi.dag.dislserver.Protocol.ControllerAction.forNumber(action_);
      return result == null ? ch.usi.dag.dislserver.Protocol.ControllerAction.UNRECOGNIZED : result;
    }
    /**
     * <code>.ControllerAction action = 1;</code>
     * @param value The enum numeric value on the wire for action to set.
     */
    private void setActionValue(int value) {
      action_ = value;
    }
    /**
     * <code>.ControllerAction action = 1;</code>
     * @param value The action to set.
     */
    private void setAction(ch.usi.dag.dislserver.Protocol.ControllerAction value) {
      action_ = value.getNumber();

    }
    /**
     * <code>.ControllerAction action = 1;</code>
     */
    private void clearAction() {

      action_ = 0;
    }

    public static final int SNIPPETNAME_FIELD_NUMBER = 2;
    private java.lang.String snippetName_;
    /**
     * <code>string snippetName = 2;</code>
     * @return The snippetName.
     */
    @java.lang.Override
    public java.lang.String getSnippetName() {
      return snippetName_;
    }
    /**
     * <code>string snippetName = 2;</code>
     * @return The bytes for snippetName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSnippetNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(snippetName_);
    }
    /**
     * <code>string snippetName = 2;</code>
     * @param value The snippetName to set.
     */
    private void setSnippetName(
            java.lang.String value) {
      value.getClass();

      snippetName_ = value;
    }
    /**
     * <code>string snippetName = 2;</code>
     */
    private void clearSnippetName() {

      snippetName_ = getDefaultInstance().getSnippetName();
    }
    /**
     * <code>string snippetName = 2;</code>
     * @param value The bytes for snippetName to set.
     */
    private void setSnippetNameBytes(
            com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      snippetName_ = value.toStringUtf8();

    }

    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.ControllerRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ControllerRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    ch.usi.dag.dislserver.Protocol.ControllerRequest, Builder> implements
            // @@protoc_insertion_point(builder_implements:ControllerRequest)
            ch.usi.dag.dislserver.Protocol.ControllerRequestOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.ControllerRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.ControllerAction action = 1;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override
      public int getActionValue() {
        return instance.getActionValue();
      }
      /**
       * <code>.ControllerAction action = 1;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        copyOnWrite();
        instance.setActionValue(value);
        return this;
      }
      /**
       * <code>.ControllerAction action = 1;</code>
       * @return The action.
       */
      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.ControllerAction getAction() {
        return instance.getAction();
      }
      /**
       * <code>.ControllerAction action = 1;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(ch.usi.dag.dislserver.Protocol.ControllerAction value) {
        copyOnWrite();
        instance.setAction(value);
        return this;
      }
      /**
       * <code>.ControllerAction action = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        copyOnWrite();
        instance.clearAction();
        return this;
      }

      /**
       * <code>string snippetName = 2;</code>
       * @return The snippetName.
       */
      @java.lang.Override
      public java.lang.String getSnippetName() {
        return instance.getSnippetName();
      }
      /**
       * <code>string snippetName = 2;</code>
       * @return The bytes for snippetName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getSnippetNameBytes() {
        return instance.getSnippetNameBytes();
      }
      /**
       * <code>string snippetName = 2;</code>
       * @param value The snippetName to set.
       * @return This builder for chaining.
       */
      public Builder setSnippetName(
              java.lang.String value) {
        copyOnWrite();
        instance.setSnippetName(value);
        return this;
      }
      /**
       * <code>string snippetName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSnippetName() {
        copyOnWrite();
        instance.clearSnippetName();
        return this;
      }
      /**
       * <code>string snippetName = 2;</code>
       * @param value The bytes for snippetName to set.
       * @return This builder for chaining.
       */
      public Builder setSnippetNameBytes(
              com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSnippetNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ControllerRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.ControllerRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
                  "action_",
                  "snippetName_",
          };
          java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                          "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.ControllerRequest> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.ControllerRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                        new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.ControllerRequest>(
                                DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ControllerRequest)
    private static final ch.usi.dag.dislserver.Protocol.ControllerRequest DEFAULT_INSTANCE;
    static {
      ControllerRequest defaultInstance = new ControllerRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
              ControllerRequest.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.ControllerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ControllerRequest> PARSER;

    public static com.google.protobuf.Parser<ControllerRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ControllerResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ControllerResponse)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.ControllerResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.ControllerResult result = 1;</code>
     * @return The result.
     */
    ch.usi.dag.dislserver.Protocol.ControllerResult getResult();

    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
    getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code ControllerResponse}
   */
  public  static final class ControllerResponse extends
          com.google.protobuf.GeneratedMessageLite<
                  ControllerResponse, ControllerResponse.Builder> implements
          // @@protoc_insertion_point(message_implements:ControllerResponse)
          ControllerResponseOrBuilder {
    private ControllerResponse() {
      errorMessage_ = "";
    }
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.ControllerResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.ControllerResult result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.ControllerResult getResult() {
      ch.usi.dag.dislserver.Protocol.ControllerResult result = ch.usi.dag.dislserver.Protocol.ControllerResult.forNumber(result_);
      return result == null ? ch.usi.dag.dislserver.Protocol.ControllerResult.UNRECOGNIZED : result;
    }
    /**
     * <code>.ControllerResult result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     */
    private void setResultValue(int value) {
      result_ = value;
    }
    /**
     * <code>.ControllerResult result = 1;</code>
     * @param value The result to set.
     */
    private void setResult(ch.usi.dag.dislserver.Protocol.ControllerResult value) {
      result_ = value.getNumber();

    }
    /**
     * <code>.ControllerResult result = 1;</code>
     */
    private void clearResult() {

      result_ = 0;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.String errorMessage_;
    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The errorMessage to set.
     */
    private void setErrorMessage(
            java.lang.String value) {
      value.getClass();

      errorMessage_ = value;
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    private void clearErrorMessage() {

      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The bytes for errorMessage to set.
     */
    private void setErrorMessageBytes(
            com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errorMessage_ = value.toStringUtf8();

    }

    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.ControllerResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.ControllerResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ControllerResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    ch.usi.dag.dislserver.Protocol.ControllerResponse, Builder> implements
            // @@protoc_insertion_point(builder_implements:ControllerResponse)
            ch.usi.dag.dislserver.Protocol.ControllerResponseOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.ControllerResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.ControllerResult result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override
      public int getResultValue() {
        return instance.getResultValue();
      }
      /**
       * <code>.ControllerResult result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        copyOnWrite();
        instance.setResultValue(value);
        return this;
      }
      /**
       * <code>.ControllerResult result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.ControllerResult getResult() {
        return instance.getResult();
      }
      /**
       * <code>.ControllerResult result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ch.usi.dag.dislserver.Protocol.ControllerResult value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>.ControllerResult result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>string errorMessage = 2;</code>
       * @return The errorMessage.
       */
      @java.lang.Override
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return The bytes for errorMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
      getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
              java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
              com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ControllerResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.ControllerResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
                  "result_",
                  "errorMessage_",
          };
          java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                          "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.ControllerResponse> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.ControllerResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                        new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.ControllerResponse>(
                                DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ControllerResponse)
    private static final ch.usi.dag.dislserver.Protocol.ControllerResponse DEFAULT_INSTANCE;
    static {
      ControllerResponse defaultInstance = new ControllerResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
              ControllerResponse.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.ControllerResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ControllerResponse> PARSER;

    public static com.google.protobuf.Parser<ControllerResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
